server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # SPA: cualquier ruta desconocida devuelve index.html
  location / {
    try_files $uri /index.html;
  }

  # Proxy al api-gateway dentro de la red de Docker
  location /api/ {
    proxy_pass http://api-gateway:4000;
    proxy_http_version 1.1;
    # SSE: sin buffering para que los eventos lleguen en tiempo real
    proxy_buffering off;
    proxy_set_header Connection '';
    proxy_read_timeout 1h;
    # Subidas grandes
    client_max_body_size 1024m;
    proxy_request_buffering off;
  }
}
